"""
Database Models - MongoDB/Pydantic
Integrated from SM-Automation + FydBlock features
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Dict
from datetime import datetime
from enum import Enum


class PostStatus(str, Enum):
    """Post workflow status"""
    DRAFT = "draft"
    APPROVED = "approved"
    PUBLISHED = "published"
    REJECTED = "rejected"


class NewsCategory(str, Enum):
    """News classification categories"""
    LAWS_REGULATIONS = "laws_regulations"
    INNOVATIONS = "innovations"
    UPDATES = "updates"
    NEW_PROJECTS = "new_projects"
    NEW_LAUNCHES = "new_launches"
    MARKET_TRENDS = "market_trends"
    INVESTMENT = "investment"


class PostType(str, Enum):
    """Post generation type"""
    COMPLETE = "complete"  # Has image + caption (from pipeline)
    BASIC = "basic"        # Just article info (for manual use)
    MANUAL = "manual"      # Created from instant search


class PostFormat(str, Enum):
    """Visual format of the post"""
    FEED = "feed"           # Standard square/portrait — existing behaviour
    STORY = "story"         # Vertical 9:16 (1080×1920)
    CAROUSEL = "carousel"   # 3-slide 4:5 (1080×1350 each)


class BackgroundProvider(str, Enum):
    """Image background source"""
    STABILITY_AI = "stability_ai"
    OPENAI_DALLE = "openai_dalle"
    PEXELS = "pexels"
    UNSPLASH = "unsplash"
    UPLOADED = "uploaded"
    GRADIENT = "gradient"


class Platform(str, Enum):
    """Social media platforms"""
    INSTAGRAM = "instagram"
    FACEBOOK = "facebook"
    TWITTER = "twitter"
    WHATSAPP = "whatsapp"
    THREADS = "threads"
    LINKEDIN = "linkedin"


class PlatformContent(BaseModel):
    """Per-platform generated content block"""
    caption: Optional[str] = None
    hashtags: Optional[List[str]] = None
    image_url: Optional[str] = None          # Platform-specific sized image
    status: PostStatus = PostStatus.DRAFT    # Per-platform publish status
    published_at: Optional[datetime] = None
    scheduled_at: Optional[datetime] = None
    platform_post_id: Optional[str] = None  # ID returned after publishing

    class Config:
        use_enum_values = True


class CarouselSlide(BaseModel):
    """Single slide within a carousel post"""
    slide_number: int                        # 1, 2, 3
    headline: Optional[str] = None          # Overlay text for this slide
    slide_caption: Optional[str] = None     # Short text angle for this slide
    background_image_url: Optional[str] = None
    final_image_url: Optional[str] = None   # Rendered slide with template overlay
    ai_prompt: Optional[str] = None


class FormatsGenerated(BaseModel):
    """Tracks which visual formats have been generated for a post"""
    feed: bool = False
    story: bool = False
    carousel: bool = False


class Post(BaseModel):
    """
    Unified Post model combining SM-Automation + FydBlock features
    """
    id: Optional[str] = Field(None, alias="_id")
    
    # ===== SOURCE INFORMATION (from news APIs) =====
    title: str
    content: str
    source_url: str
    source_name: str
    published_date: Optional[str] = None
    api_tier: Optional[str] = None  # "NewsAPI" | "EventRegistry"
    
    # ===== PROCESSING SCORES (pipeline metrics) =====
    confidence_score: Optional[float] = None
    relevance_score: Optional[float] = None
    ai_reasoning: Optional[str] = None
    
    # ===== POST CONTENT (generated by AI) =====
    headline: Optional[str] = None
    caption: Optional[str] = None           # Primary caption (Instagram feed)
    hashtags: Optional[List[str]] = None    # Primary hashtags (Instagram feed)
    full_text: Optional[str] = None
    
    # ===== FORMAT =====
    post_format: PostFormat = PostFormat.FEED

    # ===== PER-PLATFORM CONTENT =====
    # Keyed by Platform enum value: "instagram", "twitter", "whatsapp", "threads", "facebook"
    platforms: Optional[Dict[str, PlatformContent]] = None

    # ===== CAROUSEL SLIDES (populated when post_format == carousel) =====
    carousel_slides: Optional[List[CarouselSlide]] = None

    # ===== STORY IMAGE (populated when story has been generated) =====
    story_image_url: Optional[str] = None

    # ===== FORMAT GENERATION TRACKING =====
    formats_generated: Optional[FormatsGenerated] = None

    # ===== CATEGORY & CLASSIFICATION =====
    category: Optional[NewsCategory] = None
    
    # ===== IMAGE ASSETS =====
    background_image_path: Optional[str] = None
    final_image_path: Optional[str] = None
    image_url: Optional[str] = None
    image_width: Optional[int] = None
    image_height: Optional[int] = None
    
    # ===== RENDERING CONFIGURATION =====
    template_id: Optional[str] = "professional_hero"
    background_provider: Optional[BackgroundProvider] = None
    background_ref: Optional[str] = None
    green_words: Optional[str] = None
    gold_words: Optional[str] = None
    ai_prompt: Optional[str] = None
    
    # ===== STATUS & WORKFLOW =====
    status: PostStatus = PostStatus.DRAFT
    post_type: PostType = PostType.BASIC
    platform: Platform = Platform.INSTAGRAM  # Primary platform
    
    # ===== PUBLISHING =====
    scheduled_at: Optional[datetime] = None
    published_at: Optional[datetime] = None
    
    # ===== ERROR HANDLING =====
    error_message: Optional[str] = None
    
    # ===== METADATA =====
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        populate_by_name = True
        use_enum_values = True
        json_schema_extra = {
            "example": {
                "title": "Dubai Real Estate Market Sees 15% Growth",
                "content": "Dubai's real estate sector continues its remarkable growth trajectory...",
                "source_url": "https://gulfnews.com/business/property/...",
                "source_name": "Gulf News",
                "confidence_score": 85.5,
                "relevance_score": 92.0,
                "headline": "DUBAI REAL ESTATE GROWS 15% IN 2025",
                "caption": "🏢 Major milestone for Dubai's property market!",
                "hashtags": ["DubaiRealEstate", "PropertyInvestment", "UAE", "BinayahProperties"],
                "post_format": "feed",
                "platforms": {
                    "instagram": {"caption": "...", "hashtags": [], "status": "draft"},
                    "twitter":   {"caption": "...", "hashtags": [], "status": "draft"},
                    "whatsapp":  {"caption": "...", "status": "draft"},
                    "threads":   {"caption": "...", "hashtags": [], "status": "draft"},
                    "facebook":  {"caption": "...", "hashtags": [], "status": "draft"},
                },
                "green_words": "DUBAI,15%,GROWS",
                "background_provider": "stability_ai",
                "status": "draft",
                "post_type": "complete",
                "platform": "instagram"
            }
        }


class PostCreate(BaseModel):
    """Schema for creating a new post"""
    title: str
    content: str
    source_url: str
    source_name: str
    published_date: Optional[str] = None
    category: Optional[NewsCategory] = None
    post_format: PostFormat = PostFormat.FEED


class PostUpdate(BaseModel):
    """Schema for updating an existing post"""
    headline: Optional[str] = None
    caption: Optional[str] = None
    hashtags: Optional[List[str]] = None
    green_words: Optional[str] = None
    gold_words: Optional[str] = None
    status: Optional[PostStatus] = None
    category: Optional[NewsCategory] = None
    scheduled_at: Optional[datetime] = None
    post_format: Optional[PostFormat] = None
    platforms: Optional[Dict[str, PlatformContent]] = None
    carousel_slides: Optional[List[CarouselSlide]] = None
    story_image_url: Optional[str] = None
    formats_generated: Optional[FormatsGenerated] = None
    story_status: Optional[str] = None       # draft / approved
    carousel_status: Optional[str] = None    # draft / approved


class PlatformUpdate(BaseModel):
    """Request body for PATCH /platforms/{platform}"""
    caption: Optional[str] = None
    hashtags: Optional[List[str]] = None
    image_url: Optional[str] = None
    scheduled_at: Optional[datetime] = None


class ImageRegenerateRequest(BaseModel):
    """Request to regenerate post image"""
    background_type: BackgroundProvider
    ai_prompt: Optional[str] = None
    stock_query: Optional[str] = None
    uploaded_image_url: Optional[str] = None
    green_words: Optional[str] = None
    gold_words: Optional[str] = None
    headline_override: Optional[str] = None


class PipelineStats(BaseModel):
    """Pipeline execution statistics"""
    success: bool
    articles_fetched: int = 0
    articles_filtered: int = 0
    articles_validated: int = 0
    articles_ranked: int = 0
    new_articles: int = 0
    posts_created: int = 0
    complete_posts_created: int = 0
    posts_approved: int = 0
    fetch_start: Optional[str] = None
    fetch_end: Optional[str] = None
    timestamp: str
    error: Optional[str] = None


class DashboardStats(BaseModel):
    """Dashboard overview statistics"""
    total_posts: int
    draft_posts: int
    approved_posts: int
    published_posts: int
    posts_today: int
    complete_posts: int
    basic_posts: int
    last_pipeline_run: Optional[datetime] = None
    avg_confidence_score: Optional[float] = None
    avg_relevance_score: Optional[float] = None


class NewsSearchResult(BaseModel):
    """Single news search result"""
    title: str
    content: str
    url: str
    source: str
    published_date: Optional[str] = None
    image_url: Optional[str] = None
    relevance_score: Optional[float] = None


class InstantPostCreate(BaseModel):
    """Create post instantly from search result"""
    article: NewsSearchResult
    platform: Platform = Platform.INSTAGRAM
    generate_image: bool = True
    background_type: BackgroundProvider = BackgroundProvider.STABILITY_AI